spring:
  application:
    name: LojaProdutosApplication
  datasource:
    url: jdbc:h2:mem:produtodb
    driver-class-name: org.h2.Driver
    username: produto
    password: produto
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
